version: '3.8'
services:
  frontend:
    image: frontend
    build:
      args:
        - NODE_ENV=production
        - VITE_SERVER_URL=http://localhost:3030
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:80"
